apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/*.log
        - /var/log/kubernetes/*.log
    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]


